.class public final Lmb/l$a$i;
.super Lkotlin/jvm/internal/h;
.source "KClassImpl.kt"

# interfaces
.implements Ldb/a;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lmb/l$a;-><init>(Lmb/l;)V
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = null
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lkotlin/jvm/internal/h;",
        "Ldb/a<",
        "Lrb/e;",
        ">;"
    }
.end annotation


# instance fields
.field public final synthetic n:Lmb/l$a;


# direct methods
.method public constructor <init>(Lmb/l$a;)V
    .registers 2

    iput-object p1, p0, Lmb/l$a$i;->n:Lmb/l$a;

    const/4 p1, 0x0

    invoke-direct {p0, p1}, Lkotlin/jvm/internal/h;-><init>(I)V

    return-void
.end method


# virtual methods
.method public d()Ljava/lang/Object;
    .registers 5

    .line 1
    iget-object v0, p0, Lmb/l$a$i;->n:Lmb/l$a;

    iget-object v0, v0, Lmb/l$a;->m:Lmb/l;

    sget v1, Lmb/l;->r:I

    .line 2
    invoke-virtual {v0}, Lmb/l;->s()Loc/a;

    move-result-object v0

    .line 3
    iget-object v1, p0, Lmb/l$a$i;->n:Lmb/l$a;

    iget-object v1, v1, Lmb/l$a;->m:Lmb/l;

    .line 4
    iget-object v1, v1, Lmb/l;->p:Lmb/r0$b;

    .line 5
    invoke-virtual {v1}, Lmb/r0$b;->d()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lmb/l$a;

    .line 6
    iget-object v1, v1, Lmb/p$a;->a:Lmb/r0$a;

    sget-object v2, Lmb/p$a;->c:[Lkb/i;

    const/4 v3, 0x0

    aget-object v2, v2, v3

    .line 7
    invoke-virtual {v1}, Lmb/r0$a;->d()Ljava/lang/Object;

    move-result-object v1

    .line 8
    check-cast v1, Lvb/f;

    .line 9
    iget-boolean v2, v0, Loc/a;->c:Z

    if-eqz v2, :cond_2e

    .line 10
    iget-object v1, v1, Lvb/f;->a:Lcd/k;

    .line 11
    invoke-virtual {v1, v0}, Lcd/k;->b(Loc/a;)Lrb/e;

    move-result-object v0

    goto :goto_36

    .line 12
    :cond_2e
    iget-object v1, v1, Lvb/f;->a:Lcd/k;

    .line 13
    iget-object v1, v1, Lcd/k;->c:Lrb/v;

    .line 14
    invoke-static {v1, v0}, Lrb/q;->a(Lrb/v;Loc/a;)Lrb/e;

    move-result-object v0

    :goto_36
    if-eqz v0, :cond_39

    return-object v0

    .line 15
    :cond_39
    iget-object p0, p0, Lmb/l$a$i;->n:Lmb/l$a;

    iget-object p0, p0, Lmb/l$a;->m:Lmb/l;

    .line 16
    iget-object v0, p0, Lmb/l;->q:Ljava/lang/Class;

    .line 17
    invoke-static {v0}, Lvb/c;->e(Ljava/lang/Class;)Lvb/c;

    move-result-object v0

    if-eqz v0, :cond_4c

    .line 18
    iget-object v0, v0, Lvb/c;->b:Lic/a;

    if-eqz v0, :cond_4c

    .line 19
    iget-object v0, v0, Lic/a;->a:Lic/a$a;

    goto :goto_4d

    :cond_4c
    const/4 v0, 0x0

    :goto_4d
    if-eqz v0, :cond_b0

    .line 20
    sget-object v1, Lmb/o;->a:[I

    invoke-virtual {v0}, Ljava/lang/Enum;->ordinal()I

    move-result v2

    aget v1, v1, v2

    packed-switch v1, :pswitch_data_c6

    .line 21
    new-instance p0, Ls7/q;

    invoke-direct {p0}, Ls7/q;-><init>()V

    throw p0

    .line 22
    :pswitch_60
    new-instance v1, Lmb/p0;

    const-string v2, "Unknown class: "

    invoke-static {v2}, Landroid/support/v4/media/a;->b(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 23
    iget-object p0, p0, Lmb/l;->q:Ljava/lang/Class;

    .line 24
    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string p0, " (kind = "

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const/16 p0, 0x29

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v1, p0}, Lmb/p0;-><init>(Ljava/lang/String;)V

    throw v1

    .line 25
    :pswitch_82
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    const-string v1, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It\'s not a Kotlin class or interface, so the reflection "

    const-string v2, "library has no idea what declarations does it have. Please use Java reflection to inspect this class: "

    .line 26
    invoke-static {v1, v2}, Landroid/support/v4/media/a;->c(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    .line 27
    iget-object p0, p0, Lmb/l;->q:Ljava/lang/Class;

    .line 28
    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    .line 29
    invoke-direct {v0, p0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 30
    :pswitch_99
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    const-string v1, "Packages and file facades are not yet supported in Kotlin reflection. "

    const-string v2, "Meanwhile please use Java reflection to inspect this class: "

    .line 31
    invoke-static {v1, v2}, Landroid/support/v4/media/a;->c(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    .line 32
    iget-object p0, p0, Lmb/l;->q:Ljava/lang/Class;

    .line 33
    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    .line 34
    invoke-direct {v0, p0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 35
    :cond_b0
    :pswitch_b0
    new-instance v0, Lmb/p0;

    const-string v1, "Unresolved class: "

    invoke-static {v1}, Landroid/support/v4/media/a;->b(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    .line 36
    iget-object p0, p0, Lmb/l;->q:Ljava/lang/Class;

    .line 37
    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Lmb/p0;-><init>(Ljava/lang/String;)V

    throw v0

    nop

    :pswitch_data_c6
    .packed-switch 0x1
        :pswitch_99
        :pswitch_99
        :pswitch_99
        :pswitch_82
        :pswitch_60
        :pswitch_b0
    .end packed-switch
.end method
